import { SuperPropertyTile, CardAction } from '@/types/database';

export const SUPER_MONOPOLY_TILES: SuperPropertyTile[] = [
  // แถวล่าง (Bottom: 0 -> 10, จากขวาไปซ้าย)
  {
    index: 0,
    name: 'จุดเริ่มต้น',
    type: 'start',
    description: 'ผ่านหรือตกช่องนี้ รับเงินเดือน 2.0M',
    icon: '🏁',
  },
  {
    index: 1,
    name: 'นครปฐม',
    type: 'property',
    color: '#8b4513',
    cost: 0.6,
    houseCost: 0.3,
    hotelCost: 1.0,
    baseRent: 0.06,
    rent1House: 0.2,
    rent2House: 0.6,
    rent3House: 1.2,
    rentHotel: 2.5,
    icon: '🌾',
  },
  {
    index: 2,
    name: 'หีบสมบัติ',
    type: 'chest',
    description: 'เปิดการ์ดหีบสมบัติเพื่อรับรางวัลหรือโชคชะตา',
    icon: '🎁',
  },
  {
    index: 3,
    name: 'กรุงเทพฯ',
    type: 'property',
    color: '#8b4513',
    cost: 0.6,
    houseCost: 0.3,
    hotelCost: 1.0,
    baseRent: 0.06,
    rent1House: 0.2,
    rent2House: 0.6,
    rent3House: 1.2,
    rentHotel: 2.5,
    icon: '🏛️',
  },
  {
    index: 4,
    name: 'โรงแรมเอเชีย กรุงเทพฯ',
    type: 'property',
    isUtility: true,
    color: '#0284c7',
    cost: 2.0,
    baseRent: 0.4,
    description: 'โรงแรมระดับตำนานย่านราชเทวี หากมีโรงแรมในเครือเพิ่ม ค่าผ่านทางจะทวีคูณ!',
    icon: '🏨',
  },
  {
    index: 5,
    name: 'การประปานครหลวง',
    type: 'property',
    isUtility: true,
    color: '#0284c7',
    cost: 2.0,
    baseRent: 0.5,
    description: 'กิจการสาธารณูปโภคการประปา หากครอบครองทั้งการประปาและโรงไฟฟ้า ค่าผ่านทางจะเพิ่มเป็น 1.2M!',
    icon: '🚰',
  },
  {
    index: 6,
    name: 'ชลบุรี',
    type: 'property',
    color: '#00ced1',
    cost: 1.0,
    houseCost: 0.5,
    hotelCost: 1.5,
    baseRent: 0.1,
    rent1House: 0.3,
    rent2House: 0.9,
    rent3House: 1.8,
    rentHotel: 3.5,
    icon: '🏖️',
  },
  {
    index: 7,
    name: 'ประตูดวง',
    type: 'chance',
    description: 'เปิดการ์ดประตูดวง ลุ้นเหตุการณ์พลิกผัน!',
    icon: '⛩️',
  },
  {
    index: 8,
    name: 'ระยอง',
    type: 'property',
    color: '#00ced1',
    cost: 1.0,
    houseCost: 0.5,
    hotelCost: 1.5,
    baseRent: 0.1,
    rent1House: 0.3,
    rent2House: 0.9,
    rent3House: 1.8,
    rentHotel: 3.5,
    icon: '🏭',
  },
  {
    index: 9,
    name: 'จันทบุรี',
    type: 'property',
    color: '#00ced1',
    cost: 1.2,
    houseCost: 0.6,
    hotelCost: 1.8,
    baseRent: 0.12,
    rent1House: 0.35,
    rent2House: 1.0,
    rent3House: 2.0,
    rentHotel: 4.0,
    icon: '💎',
  },
  {
    index: 10,
    name: 'ช่องเข้าคุก',
    type: 'jail',
    description: 'คุกคุมขัง / ผู้มาเยือน หากไม่ได้ถูกส่งเข้าคุก แวะมาเยี่ยมเพื่อนได้ตามสบาย',
    icon: '⛓️',
  },

  // แถวซ้าย (Left: 10 -> 20, จากล่างขึ้นบน)
  {
    index: 11,
    name: 'กาญจนบุรี',
    type: 'property',
    color: '#ff1493',
    cost: 1.4,
    houseCost: 0.7,
    hotelCost: 2.0,
    baseRent: 0.14,
    rent1House: 0.45,
    rent2House: 1.3,
    rent3House: 2.5,
    rentHotel: 5.0,
    icon: '🌉',
  },
  {
    index: 12,
    name: 'โรงไฟฟ้านครหลวง',
    type: 'property',
    isUtility: true,
    color: '#eab308',
    cost: 2.0,
    baseRent: 0.5,
    description: 'กิจการสาธารณูปโภคโรงไฟฟ้า หากครอบครองทั้งการประปาและโรงไฟฟ้า ค่าผ่านทางจะเพิ่มเป็น 1.2M!',
    icon: '⚡',
  },
  {
    index: 13,
    name: 'ประจวบคีรีขันธ์',
    type: 'property',
    color: '#ff1493',
    cost: 1.4,
    houseCost: 0.7,
    hotelCost: 2.0,
    baseRent: 0.14,
    rent1House: 0.45,
    rent2House: 1.3,
    rent3House: 2.5,
    rentHotel: 5.0,
    icon: '🏝️',
  },
  {
    index: 14,
    name: 'เพชรบุรี',
    type: 'property',
    color: '#ff1493',
    cost: 1.6,
    houseCost: 0.8,
    hotelCost: 2.4,
    baseRent: 0.16,
    rent1House: 0.5,
    rent2House: 1.5,
    rent3House: 3.0,
    rentHotel: 6.0,
    icon: '🌴',
  },
  {
    index: 15,
    name: 'โรงแรมดุสิตธานี',
    type: 'property',
    isUtility: true,
    color: '#0284c7',
    cost: 2.0,
    baseRent: 0.4,
    description: 'โรงแรมหรูระดับ 5 ดาวแลนด์มาร์กกรุงเทพฯ หากมีโรงแรมในเครือเพิ่ม ค่าผ่านทางจะทวีคูณ!',
    icon: '🏨',
  },
  {
    index: 16,
    name: 'สุราษฎร์ธานี',
    type: 'property',
    color: '#ff8c00',
    cost: 1.8,
    houseCost: 0.9,
    hotelCost: 2.7,
    baseRent: 0.18,
    rent1House: 0.55,
    rent2House: 1.6,
    rent3House: 3.2,
    rentHotel: 6.5,
    icon: '🥥',
  },
  {
    index: 17,
    name: 'หีบสมบัติ',
    type: 'chest',
    description: 'เปิดการ์ดหีบสมบัติเพื่อรับรางวัลหรือโชคชะตา',
    icon: '🎁',
  },
  {
    index: 18,
    name: 'กระบี่',
    type: 'property',
    color: '#ff8c00',
    cost: 1.8,
    houseCost: 0.9,
    hotelCost: 2.7,
    baseRent: 0.18,
    rent1House: 0.55,
    rent2House: 1.6,
    rent3House: 3.2,
    rentHotel: 6.5,
    icon: '⛵',
  },
  {
    index: 19,
    name: 'ภูเก็ต',
    type: 'property',
    color: '#ff8c00',
    cost: 2.0,
    houseCost: 1.0,
    hotelCost: 3.0,
    baseRent: 0.2,
    rent1House: 0.6,
    rent2House: 1.8,
    rent3House: 3.5,
    rentHotel: 7.0,
    icon: '🏖️',
  },
  {
    index: 20,
    name: 'จุดพักผ่อน',
    type: 'parking',
    description: 'จุดพักผ่อนริมชายหาด ปลอดภัยจากค่าผ่านทาง และเดินต่อได้ตามปกติ',
    icon: '🏖️',
  },

  // แถวบน (Top: 20 -> 30, จากซ้ายไปขวา)
  {
    index: 21,
    name: 'พิษณุโลก',
    type: 'property',
    color: '#e60000',
    cost: 2.2,
    houseCost: 1.1,
    hotelCost: 3.3,
    baseRent: 0.22,
    rent1House: 0.7,
    rent2House: 2.0,
    rent3House: 4.0,
    rentHotel: 8.0,
    icon: '⚔️',
  },
  {
    index: 22,
    name: 'ประตูดวง',
    type: 'chance',
    description: 'เปิดการ์ดประตูดวง ลุ้นเหตุการณ์พลิกผัน!',
    icon: '⛩️',
  },
  {
    index: 23,
    name: 'สุโขทัย',
    type: 'property',
    color: '#e60000',
    cost: 2.2,
    houseCost: 1.1,
    hotelCost: 3.3,
    baseRent: 0.22,
    rent1House: 0.7,
    rent2House: 2.0,
    rent3House: 4.0,
    rentHotel: 8.0,
    icon: '🛕',
  },
  {
    index: 24,
    name: 'นครสวรรค์',
    type: 'property',
    color: '#e60000',
    cost: 2.4,
    houseCost: 1.2,
    hotelCost: 3.6,
    baseRent: 0.24,
    rent1House: 0.75,
    rent2House: 2.2,
    rent3House: 4.2,
    rentHotel: 8.5,
    icon: '🐉',
  },
  {
    index: 25,
    name: 'โรงแรมเซ็นทารา แกรนด์',
    type: 'property',
    isUtility: true,
    color: '#0284c7',
    cost: 2.0,
    baseRent: 0.4,
    description: 'โรงแรมหรูชั้นนำระดับแนวหน้าของไทย หากมีโรงแรมในเครือเพิ่ม ค่าผ่านทางจะทวีคูณ!',
    icon: '🏨',
  },
  {
    index: 26,
    name: 'โรงแรมสยามเคมปินสกี้',
    type: 'property',
    isUtility: true,
    color: '#0284c7',
    cost: 2.4,
    baseRent: 0.45,
    description: 'โรงแรม 5 ดาวระดับอัลตร้าลักชูรีใจกลางสยาม หากมีโรงแรมในเครือเพิ่ม ค่าผ่านทางจะทวีคูณ!',
    icon: '🏨',
  },
  {
    index: 27,
    name: 'ลำปาง',
    type: 'property',
    color: '#ffd700',
    cost: 2.6,
    houseCost: 1.3,
    hotelCost: 3.9,
    baseRent: 0.26,
    rent1House: 0.8,
    rent2House: 2.3,
    rent3House: 4.5,
    rentHotel: 9.0,
    icon: '🐎',
  },
  {
    index: 28,
    name: 'เชียงราย',
    type: 'property',
    color: '#ffd700',
    cost: 2.6,
    houseCost: 1.3,
    hotelCost: 3.9,
    baseRent: 0.26,
    rent1House: 0.8,
    rent2House: 2.3,
    rent3House: 4.5,
    rentHotel: 9.0,
    icon: '⛰️',
  },
  {
    index: 29,
    name: 'เชียงใหม่',
    type: 'property',
    color: '#ffd700',
    cost: 2.8,
    houseCost: 1.4,
    hotelCost: 4.2,
    baseRent: 0.28,
    rent1House: 0.9,
    rent2House: 2.5,
    rent3House: 5.0,
    rentHotel: 10.0,
    icon: '🐘',
  },
  {
    index: 30,
    name: 'ช่องไปเข้าคุก',
    type: 'go_to_jail',
    description: 'ติดคุกทันที! โดนตำรวจจับส่งเข้าห้องขังที่ช่อง 10',
    icon: '👮',
  },

  // แถวขวา (Right: 30 -> 39, จากบนลงล่าง)
  {
    index: 31,
    name: 'อุดรธานี',
    type: 'property',
    color: '#32cd32',
    cost: 3.0,
    houseCost: 1.5,
    hotelCost: 4.5,
    baseRent: 0.3,
    rent1House: 1.0,
    rent2House: 2.8,
    rent3House: 5.5,
    rentHotel: 11.0,
    icon: '🌸',
  },
  {
    index: 32,
    name: 'ขอนแก่น',
    type: 'property',
    color: '#32cd32',
    cost: 3.0,
    houseCost: 1.5,
    hotelCost: 4.5,
    baseRent: 0.3,
    rent1House: 1.0,
    rent2House: 2.8,
    rent3House: 5.5,
    rentHotel: 11.0,
    icon: '🦕',
  },
  {
    index: 33,
    name: 'หีบสมบัติ',
    type: 'chest',
    description: 'เปิดการ์ดหีบสมบัติเพื่อรับรางวัลหรือโชคชะตา',
    icon: '🎁',
  },
  {
    index: 34,
    name: 'นครราชสีมา',
    type: 'property',
    color: '#32cd32',
    cost: 3.2,
    houseCost: 1.6,
    hotelCost: 4.8,
    baseRent: 0.32,
    rent1House: 1.1,
    rent2House: 3.0,
    rent3House: 6.0,
    rentHotel: 12.0,
    icon: '🏰',
  },
  {
    index: 35,
    name: 'โรงแรมแมนดาริน โอเรียนเต็ล',
    type: 'property',
    isUtility: true,
    color: '#0284c7',
    cost: 2.5,
    baseRent: 0.5,
    description: 'โรงแรมระดับตำนานริมแม่น้ำเจ้าพระยา ติดอันดับโลก หากมีโรงแรมในเครือเพิ่ม ค่าผ่านทางจะทวีคูณ!',
    icon: '🏨',
  },
  {
    index: 36,
    name: 'ประตูดวง',
    type: 'chance',
    description: 'เปิดการ์ดประตูดวง ลุ้นเหตุการณ์พลิกผัน!',
    icon: '⛩️',
  },
  {
    index: 37,
    name: 'สงขลา',
    type: 'property',
    color: '#15803d',
    cost: 3.5,
    houseCost: 1.75,
    hotelCost: 5.25,
    baseRent: 0.35,
    rent1House: 1.2,
    rent2House: 3.2,
    rent3House: 6.5,
    rentHotel: 13.0,
    icon: '🌊',
  },
  {
    index: 38,
    name: 'เสียภาษีรายได้',
    type: 'tax',
    description: 'จ่ายภาษีรายได้เข้ารัฐ 1.0M',
    icon: '💰',
  },
  {
    index: 39,
    name: 'พระนครศรีอยุธยา',
    type: 'property',
    color: '#15803d',
    cost: 4.0,
    houseCost: 2.0,
    hotelCost: 6.0,
    baseRent: 0.4,
    rent1House: 1.5,
    rent2House: 4.0,
    rent3House: 8.0,
    rentHotel: 16.0,
    icon: '🏛️',
  },
];

export const CHEST_CARDS: CardAction[] = [
  {
    id: 'ch-1',
    type: 'chest',
    title: 'รับมรดกจากเจ้าคุณปู่',
    description: 'ได้รับส่วนแบ่งมรดกที่ดินโบราณ ได้รับเงิน 2.0M',
    rewardMoney: 2.0,
  },
  {
    id: 'ch-2',
    type: 'chest',
    title: 'ถูกสลากกินแบ่งรัฐบาล',
    description: 'เลขท้ายตรงเผง รับเงินรางวัล 1.5M',
    rewardMoney: 1.5,
  },
  {
    id: 'ch-3',
    type: 'chest',
    title: 'จ่ายค่าบำรุงรักษาบ้าน',
    description: 'พายุเข้าหลังคาบ้านรั่ว จ่ายค่าซ่อมแซม 1.0M',
    rewardMoney: -1.0,
  },
  {
    id: 'ch-4',
    type: 'chest',
    title: 'วันเกิดแสนสุข',
    description: 'เพื่อนทุกคนในวงร่วมฉลอง มอบของขวัญให้คนละ 0.5M',
    collectFromAll: 0.5,
  },
  {
    id: 'ch-5',
    type: 'chest',
    title: 'เงินปันผลสหกรณ์',
    description: 'ผลกำไรจากการลงทุนประจำปี ได้รับเงิน 1.0M',
    rewardMoney: 1.0,
  },
  {
    id: 'ch-6',
    type: 'chest',
    title: 'ตรวจสุขภาพประจำปี',
    description: 'จ่ายค่าหมอและวิตามินบำรุงร่างกาย 0.5M',
    rewardMoney: -0.5,
  },
  {
    id: 'ch-7',
    type: 'chest',
    title: 'ขายที่ดินแปลงชานเมือง',
    description: 'เทศบาลเวนคืนที่ดินที่ไม่ได้ใช้ รับเงิน 1.2M',
    rewardMoney: 1.2,
  },
  {
    id: 'ch-8',
    type: 'chest',
    title: 'ค่าส่วนกลางหมู่บ้าน',
    description: 'ถึงรอบเก็บค่าส่วนกลางประจำปี จ่าย 0.7M',
    rewardMoney: -0.7,
  },
  {
    id: 'ch-9',
    type: 'chest',
    title: 'ถูกหวยรางวัลที่ 2',
    description: 'ดวงเฮียนเกินคาด รับเงินรางวัล 3.0M',
    rewardMoney: 3.0,
  },
  {
    id: 'ch-10',
    type: 'chest',
    title: 'จ่ายค่าเทอร์มินอลขนส่ง',
    description: 'ค่าขนส่งวัสดุก่อสร้างพุ่งสูง จ่าย 1.5M',
    rewardMoney: -1.5,
  },
  {
    id: 'ch-11',
    type: 'chest',
    title: 'เลี้ยงฉลองทั้งวง',
    description: 'คุณเป็นเจ้ามือ จ่ายให้เพื่อนทุกคนคนละ 0.4M',
    payToAll: 0.4,
  },
  {
    id: 'ch-12',
    type: 'chest',
    title: 'ขายหุ้นได้กำไร',
    description: 'พอร์ตโฟลิโต ขายทำกำไร รับเงิน 0.8M',
    rewardMoney: 0.8,
  },
];

export const CHANCE_CARDS: CardAction[] = [
  {
    id: 'cc-1',
    type: 'chance',
    title: 'เดินทางด่วนสู่จุดเริ่มต้น',
    description: 'ขึ้นรถไฟความเร็วสูงกลับไปยังจุดเริ่มต้นทันที รับ 2.0M',
    teleportToIndex: 0,
    rewardMoney: 2.0,
  },
  {
    id: 'cc-2',
    type: 'chance',
    title: 'บินลัดฟ้าไปอุดรธานี',
    description: 'ได้ตั๋วเครื่องบินฟรี มุ่งตรงไปลงทุนที่อุดรธานีทันที (ถ้าผ่านจุดเริ่มต้นรับ 2.0M)',
    teleportToIndex: 31,
  },
  {
    id: 'cc-3',
    type: 'chance',
    title: 'ซิ่งรถฝ่าไฟแดง',
    description: 'โดนตำรวจจราจรจับ ปรับเงิน 0.8M',
    rewardMoney: -0.8,
  },
  {
    id: 'cc-4',
    type: 'chance',
    title: 'โดนหมายศาลเรียกตัว!',
    description: 'ถูกสั่งขังเข้าคุกทันที ไม่ได้รับเงินเดือนใดๆ ทั้งสิ้น',
    goJail: true,
  },
  {
    id: 'cc-5',
    type: 'chance',
    title: 'ค่าผ่านทางสะพานข้ามเกาะ',
    description: 'จ่ายค่าธรรมเนียมบำรุงสะพาน 0.6M',
    rewardMoney: -0.6,
  },
  {
    id: 'cc-6',
    type: 'chance',
    title: 'ที่ดินราคาพุ่งกระฉูด',
    description: 'เก็งกำไรที่ดินสำเร็จ ได้รับผลตอบแทน 2.5M',
    rewardMoney: 2.5,
  },
  {
    id: 'cc-7',
    type: 'chance',
    title: 'ตรวจพบสิ่งผิดกฎหมาย',
    description: 'เจ้าหน้าที่เรียกคุย ถูกส่งเข้าห้องขังทันที',
    goJail: true,
  },
  {
    id: 'cc-8',
    type: 'chance',
    title: 'เงินปันผลหุ้นก้อนโต',
    description: 'หุ้นที่ถือไว้ราคาพุ่ง รับเงิน 1.8M',
    rewardMoney: 1.8,
  },
  {
    id: 'cc-9',
    type: 'chance',
    title: 'กลับไปตั้งหลักที่เชียงใหม่',
    description: 'ย้ายฐานการค้าไปเชียงใหม่ทันที (ถ้าผ่านจุดเริ่มต้นรับ 2.00M)',
    teleportToIndex: 21,
  },
  {
    id: 'cc-10',
    type: 'chance',
    title: 'ค่าซ่อมรถครั้งใหญ่',
    description: 'เครื่องพังกลางทาง จ่ายค่าซ่อม 1.2M',
    rewardMoney: -1.2,
  },
  {
    id: 'cc-11',
    type: 'chance',
    title: 'ได้งานประมูลเทศบาล',
    description: 'รับเหมาสร้างถนน กำไรงาม รับเงิน 2.2M',
    rewardMoney: 2.2,
  },
  {
    id: 'cc-12',
    type: 'chance',
    title: 'เรียกคืนภาษีย้อนหลัง',
    description: 'สรรพากรใจดี เก็บเงินจากเพื่อนทุกคน คนละ 0.3M',
    collectFromAll: 0.3,
  },
];

export function formatMoneyM(amount: number): string {
  // Always two decimals so every cash figure on screen lines up (15.00M, 1.40M, 0.60M)
  const rounded = Math.round(amount * 100) / 100;
  return `${rounded.toFixed(2)}M`;
}

// ---------------------------------------------------------------------------
// Draw piles
//
// Cards used to be picked at random every time, so the same one came up again
// and again. Each deck is now dealt out: a card is only reshuffled back in once
// the whole pile has been used. The remaining ids live in game_state so every
// client draws from the same pile.
// ---------------------------------------------------------------------------

function shuffleIds(cards: CardAction[]): string[] {
  const ids = cards.map((c) => c.id);
  for (let i = ids.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [ids[i], ids[j]] = [ids[j], ids[i]];
  }
  return ids;
}

export function drawFromDeck(
  deck: string[] | undefined | null,
  cards: CardAction[]
): { card: CardAction; nextDeck: string[] } {
  let pile = Array.isArray(deck) ? deck.filter((id) => cards.some((c) => c.id === id)) : [];
  if (pile.length === 0) pile = shuffleIds(cards);

  const [drawnId, ...rest] = pile;
  const card = cards.find((c) => c.id === drawnId) || cards[0];
  return { card, nextDeck: rest };
}
