import { SuperPropertyTile, CardAction } from '@/types/database';

export const SUPER_MONOPOLY_TILES: SuperPropertyTile[] = [
  // ด้านล่าง (Bottom: 0 -> 8, จากขวาไปซ้าย)
  {
    index: 0,
    name: 'จุดเริ่มต้น',
    type: 'start',
    description: 'ผ่านหรือตกช่องนี้ รับเงินเดือน 2.0M',
    icon: '🏁',
  },
  {
    index: 1,
    name: 'กรุงเทพฯ',
    type: 'property',
    color: '#8b4513',
    cost: 0.6,
    houseCost: 0.3,
    hotelCost: 1.0,
    baseRent: 0.06,
    rent1House: 0.2,
    rent2House: 0.6,
    rent3House: 1.2,
    rentHotel: 2.5,
    icon: '🏛️',
  },
  {
    index: 2,
    name: 'หีบสมบัติ',
    type: 'chest',
    description: 'เปิดการ์ดหีบสมบัติเพื่อรับรางวัลหรือโชคชะตา',
    icon: '🎁',
  },
  {
    index: 3,
    name: 'นครปฐม',
    type: 'property',
    color: '#8b4513',
    cost: 0.6,
    houseCost: 0.3,
    hotelCost: 1.0,
    baseRent: 0.06,
    rent1House: 0.2,
    rent2House: 0.6,
    rent3House: 1.2,
    rentHotel: 2.5,
    icon: '🌾',
  },
  {
    index: 4,
    name: 'การประปา',
    type: 'property',
    isUtility: true,
    color: '#0284c7',
    cost: 2.0,
    baseRent: 0.5,
    description: 'กิจการการประปา (สาธารณูปโภค) หากครอบครองทั้งการประปาและโรงไฟฟ้า ค่าผ่านทางจะเพิ่มเป็น 1.2M!',
    icon: '🚰',
  },
  {
    index: 5,
    name: 'ตลาดโบ๊เบ๊',
    type: 'property',
    color: '#00ced1',
    cost: 1.0,
    houseCost: 0.5,
    hotelCost: 1.5,
    baseRent: 0.1,
    rent1House: 0.3,
    rent2House: 0.9,
    rent3House: 1.8,
    rentHotel: 3.5,
    icon: '🛍️',
  },
  {
    index: 6,
    name: 'ประตูดวง',
    type: 'chance',
    description: 'เปิดการ์ดประตูดวง ลุ้นเหตุการณ์พลิกผัน!',
    icon: '⛩️',
  },
  {
    index: 7,
    name: 'จันทบุรี',
    type: 'property',
    color: '#00ced1',
    cost: 1.2,
    houseCost: 0.6,
    hotelCost: 1.8,
    baseRent: 0.12,
    rent1House: 0.35,
    rent2House: 1.0,
    rent3House: 2.0,
    rentHotel: 4.0,
    icon: '💎',
  },
  {
    index: 8,
    name: 'คุก / เยี่ยมคุก',
    type: 'jail',
    description: 'ช่องคุก หากไม่ได้ถูกส่งเข้าคุก แวะมาเยี่ยมเพื่อนได้ตามสบาย',
    icon: '⛓️',
  },

  // ด้านซ้าย (Left: 9 -> 16, จากล่างขึ้นบน)
  {
    index: 9,
    name: 'กาญจนบุรี',
    type: 'property',
    color: '#ff1493',
    cost: 1.4,
    houseCost: 0.7,
    hotelCost: 2.0,
    baseRent: 0.15,
    rent1House: 0.45,
    rent2House: 1.3,
    rent3House: 2.5,
    rentHotel: 5.0,
    icon: '🌉',
  },
  {
    index: 10,
    name: 'สุพรรณบุรี',
    type: 'property',
    color: '#ff1493',
    cost: 1.4,
    houseCost: 0.7,
    hotelCost: 2.0,
    baseRent: 0.15,
    rent1House: 0.45,
    rent2House: 1.3,
    rent3House: 2.5,
    rentHotel: 5.0,
    icon: '🌾',
  },
  {
    index: 11,
    name: 'ราชบุรี',
    type: 'property',
    color: '#ff1493',
    cost: 1.6,
    houseCost: 0.8,
    hotelCost: 2.4,
    baseRent: 0.18,
    rent1House: 0.5,
    rent2House: 1.5,
    rent3House: 3.0,
    rentHotel: 6.0,
    icon: '🏺',
  },
  {
    index: 12,
    name: 'โรงไฟฟ้า',
    type: 'property',
    isUtility: true,
    color: '#eab308',
    cost: 2.0,
    baseRent: 0.5,
    description: 'กิจการโรงไฟฟ้า (สาธารณูปโภค) หากครอบครองทั้งการประปาและโรงไฟฟ้า ค่าผ่านทางจะเพิ่มเป็น 1.2M!',
    icon: '⚡',
  },
  {
    index: 13,
    name: 'เพชรบุรี',
    type: 'property',
    color: '#ff8c00',
    cost: 1.8,
    houseCost: 0.9,
    hotelCost: 2.7,
    baseRent: 0.2,
    rent1House: 0.6,
    rent2House: 1.8,
    rent3House: 3.5,
    rentHotel: 7.0,
    icon: '🌴',
  },
  {
    index: 14,
    name: 'หีบสมบัติ',
    type: 'chest',
    description: 'เปิดการ์ดหีบสมบัติเพื่อรับรางวัลหรือโชคชะตา',
    icon: '🎁',
  },
  {
    index: 15,
    name: 'หัวหิน',
    type: 'property',
    color: '#ff8c00',
    cost: 2.0,
    houseCost: 1.0,
    hotelCost: 3.0,
    baseRent: 0.22,
    rent1House: 0.7,
    rent2House: 2.0,
    rent3House: 4.0,
    rentHotel: 8.0,
    icon: '🏖️',
  },
  {
    index: 16,
    name: 'จุดพักผ่อน',
    type: 'parking',
    description: 'แวะพักผ่อน ปลอดภัย ไม่ต้องเสียเงินใดๆ',
    icon: '🅿️',
  },

  // ด้านบน (Top: 17 -> 24, จากซ้ายไปขวา)
  {
    index: 17,
    name: 'ประตูดวง',
    type: 'chance',
    description: 'เปิดการ์ดประตูดวง ลุ้นเหตุการณ์พลิกผัน!',
    icon: '⛩️',
  },
  {
    index: 18,
    name: 'ชลบุรี',
    type: 'property',
    color: '#e60000',
    cost: 2.2,
    houseCost: 1.1,
    hotelCost: 3.3,
    baseRent: 0.25,
    rent1House: 0.8,
    rent2House: 2.3,
    rent3House: 4.5,
    rentHotel: 9.0,
    icon: '🌊',
  },
  {
    index: 19,
    name: 'พัทยา',
    type: 'property',
    color: '#e60000',
    cost: 2.4,
    houseCost: 1.2,
    hotelCost: 3.6,
    baseRent: 0.28,
    rent1House: 0.9,
    rent2House: 2.5,
    rent3House: 5.0,
    rentHotel: 10.0,
    icon: '⛵',
  },
  {
    index: 20,
    name: 'ขอนแก่น',
    type: 'property',
    color: '#e60000',
    cost: 2.4,
    houseCost: 1.2,
    hotelCost: 3.6,
    baseRent: 0.28,
    rent1House: 0.9,
    rent2House: 2.5,
    rent3House: 5.0,
    rentHotel: 10.0,
    icon: '🦕',
  },
  {
    index: 21,
    name: 'นครราชสีมา',
    type: 'property',
    color: '#ffd700',
    cost: 2.6,
    houseCost: 1.3,
    hotelCost: 3.9,
    baseRent: 0.3,
    rent1House: 1.0,
    rent2House: 2.8,
    rent3House: 5.5,
    rentHotel: 11.0,
    icon: '🏰',
  },
  {
    index: 22,
    name: 'อุดรธานี',
    type: 'property',
    color: '#ffd700',
    cost: 2.6,
    houseCost: 1.3,
    hotelCost: 3.9,
    baseRent: 0.3,
    rent1House: 1.0,
    rent2House: 2.8,
    rent3House: 5.5,
    rentHotel: 11.0,
    icon: '🌺',
  },
  {
    index: 23,
    name: 'เสียภาษี',
    type: 'tax',
    description: 'เสียภาษีให้รัฐ 1.5M',
    icon: '📜',
  },
  {
    index: 24,
    name: 'ไปเข้าคุกทันที',
    type: 'go_to_jail',
    description: 'โดนตำรวจจับส่งเข้าห้องขังทันที!',
    icon: '👮',
  },

  // ด้านขวา (Right: 25 -> 31, จากบนลงล่าง)
  {
    index: 25,
    name: 'อุบลราชธานี',
    type: 'property',
    color: '#32cd32',
    cost: 3.0,
    houseCost: 1.5,
    hotelCost: 4.5,
    baseRent: 0.35,
    rent1House: 1.2,
    rent2House: 3.2,
    rent3House: 6.5,
    rentHotel: 13.0,
    icon: '🕯️',
  },
  {
    index: 26,
    name: 'หีบสมบัติ',
    type: 'chest',
    description: 'เปิดการ์ดหีบสมบัติเพื่อรับรางวัลหรือโชคชะตา',
    icon: '🎁',
  },
  {
    index: 27,
    name: 'หาดใหญ่',
    type: 'property',
    color: '#32cd32',
    cost: 3.2,
    houseCost: 1.6,
    hotelCost: 4.8,
    baseRent: 0.38,
    rent1House: 1.3,
    rent2House: 3.5,
    rent3House: 7.0,
    rentHotel: 14.0,
    icon: '🏢',
  },
  {
    index: 28,
    name: 'ประตูดวง',
    type: 'chance',
    description: 'เปิดการ์ดประตูดวง ลุ้นเหตุการณ์พลิกผัน!',
    icon: '⛩️',
  },
  {
    index: 29,
    name: 'เชียงใหม่',
    type: 'property',
    color: '#15803d',
    cost: 3.5,
    houseCost: 1.75,
    hotelCost: 5.25,
    baseRent: 0.45,
    rent1House: 1.5,
    rent2House: 4.0,
    rent3House: 8.0,
    rentHotel: 16.0,
    icon: '🐘',
  },
  {
    index: 30,
    name: 'ภูเก็ต',
    type: 'property',
    color: '#15803d',
    cost: 4.0,
    houseCost: 2.0,
    hotelCost: 6.0,
    baseRent: 0.55,
    rent1House: 1.8,
    rent2House: 4.8,
    rent3House: 9.5,
    rentHotel: 19.0,
    icon: '🏝️',
  },
  {
    index: 31,
    name: 'ภาษีรายได้',
    type: 'tax',
    description: 'จ่ายภาษีรายได้ 1.0M',
    icon: '💰',
  },
];

export const CHEST_CARDS: CardAction[] = [
  {
    id: 'ch-1',
    type: 'chest',
    title: 'รับมรดกจากเจ้าคุณปู่',
    description: 'ได้รับส่วนแบ่งมรดกที่ดินโบราณ ได้รับเงิน 2.0M',
    rewardMoney: 2.0,
  },
  {
    id: 'ch-2',
    type: 'chest',
    title: 'ถูกสลากกินแบ่งรัฐบาล',
    description: 'เลขท้ายตรงเผง รับเงินรางวัล 1.5M',
    rewardMoney: 1.5,
  },
  {
    id: 'ch-3',
    type: 'chest',
    title: 'จ่ายค่าบำรุงรักษาบ้าน',
    description: 'พายุเข้าหลังคาบ้านรั่ว จ่ายค่าซ่อมแซม 1.0M',
    rewardMoney: -1.0,
  },
  {
    id: 'ch-4',
    type: 'chest',
    title: 'วันเกิดแสนสุข',
    description: 'เพื่อนทุกคนในวงร่วมฉลอง มอบของขวัญให้คนละ 0.5M',
    collectFromAll: 0.5,
  },
  {
    id: 'ch-5',
    type: 'chest',
    title: 'เงินปันผลสหกรณ์',
    description: 'ผลกำไรจากการลงทุนประจำปี ได้รับเงิน 1.0M',
    rewardMoney: 1.0,
  },
  {
    id: 'ch-6',
    type: 'chest',
    title: 'ตรวจสุขภาพประจำปี',
    description: 'จ่ายค่าหมอและวิตามินบำรุงร่างกาย 0.5M',
    rewardMoney: -0.5,
  },
];

export const CHANCE_CARDS: CardAction[] = [
  {
    id: 'cc-1',
    type: 'chance',
    title: 'เดินทางด่วนสู่จุดเริ่มต้น',
    description: 'ขึ้นรถไฟความเร็วสูงกลับไปยังจุดเริ่มต้นทันที รับ 2.0M',
    teleportToIndex: 0,
    rewardMoney: 2.0,
  },
  {
    id: 'cc-2',
    type: 'chance',
    title: 'บินลัดฟ้าไปภูเก็ต',
    description: 'ได้ตั๋วเครื่องบินฟรี มุ่งตรงไปพักผ่อนที่ภูเก็ตทันที (ถ้าผ่านจุดเริ่มต้นรับ 2.0M)',
    teleportToIndex: 31,
  },
  {
    id: 'cc-3',
    type: 'chance',
    title: 'ซิ่งรถฝ่าไฟแดง',
    description: 'โดนตำรวจจราจรจับ ปรับเงิน 0.8M',
    rewardMoney: -0.8,
  },
  {
    id: 'cc-4',
    type: 'chance',
    title: 'โดนหมายศาลเรียกตัว!',
    description: 'ถูกสั่งขังเข้าคุกทันที ไม่ได้รับเงินเดือนใดๆ ทั้งสิ้น',
    goJail: true,
  },
  {
    id: 'cc-5',
    type: 'chance',
    title: 'ค่าผ่านทางสะพานข้ามเกาะ',
    description: 'จ่ายค่าธรรมเนียมบำรุงสะพาน 0.6M',
    rewardMoney: -0.6,
  },
  {
    id: 'cc-6',
    type: 'chance',
    title: 'ที่ดินราคาพุ่งกระฉูด',
    description: 'เก็งกำไรที่ดินสำเร็จ ได้รับผลตอบแทน 2.5M',
    rewardMoney: 2.5,
  },
];

export function formatMoneyM(amount: number): string {
  if (Math.abs(amount) >= 1) {
    // e.g. 1.5M, 15M, 100M
    const formatted = (Math.round(amount * 100) / 100).toFixed(amount % 1 === 0 ? 0 : 1);
    return `${formatted}M`;
  }
  // If less than 1M, show as decimals or thousands e.g. 0.5M
  return `${amount.toFixed(2)}M`;
}
